{
 "title": "Internet-2 Tech-24 Draft",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "gnmic_srl_if_stats_in_octets", "legendFormat": "__auto" },
    { "expr": "gnmic_srl_if_stats_out_octets", "legendFormat": "__auto" },
    { "expr": "gnmic_sros_if_stats_in_octets", "legendFormat": "__auto" },
    { "expr": "gnmic_sros_if_stats_out_octets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Topology",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    },
    { "expr": "gnmic_sros_if_stats_in_octets", "legendFormat": "{{source}}:{{port_port_id}}:in" },
    {
     "expr": "gnmic_sros_if_stats_out_octets",
     "legendFormat": "{{source}}:{{port_port_id}}:out"
    }
   ]
  },
  {
   "title": "SR Linux Port Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_if_oper_state_oper_state",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 12 },
   "targets": [
    { "expr": "gnmic_sros_cpu_cpu_usage", "legendFormat": "__auto" },
    { "expr": "gnmic_srl_cpu_instant", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nokia SROS Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnmic_sros_mem_in_use", "legendFormat": "__auto" },
    { "expr": "gnmic_srl_mem_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "$Node CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_cpu_cpu_usage{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Node Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_mem_in_use{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Node Interfaces Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gnmic_sros_if_stats_in_octets{source=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_sros_if_stats_out_octets{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}