{
 "title": "mohammad1",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Traffic Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "gnmic_srl_if_stats_in_octets", "legendFormat": "__auto" },
    { "expr": "gnmic_srl_if_stats_out_octets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nokia SROS Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_mem_available_memory",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SR Linux PE2 CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnmic_srl_cpu_instant", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SR Linux PE2 CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "gnmic_srl_cpu_instant", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nokia SROS CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "gnmic_sros_cpu_cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}